operator:
    address: 0x682F5c4Bc85fEeC8D042D324960318553a47B24D
    earnings_receiver_address: 0x682F5c4Bc85fEeC8D042D324960318553a47B24D
    delegation_approver_address: "0x0000000000000000000000000000000000000000"
    staker_opt_out_window_blocks: 0
    metadata_url: ""
el_delegation_manager_address: 0xA44151489861Fe9e3055d95adC98FbD462B948e7
eth_rpc_url: https://ethereum-holesky-rpc.publicnode.com
private_key_store_path: /root/.eigenlayer/operator_keys/cherry.ecdsa.key.json
signer_type: local_keystore
chain_id: 17000
fireblocks:
    api_key: ""
    secret_key: ""
    base_url: ""
    vault_account_name: ""
    secret_storage_type: ""
    aws_region: ""
    timeout: 0
web3:
    url: ""
